version: '3.7'

services:
  ros2:
    build:
      context: ./
      args:
        distro: "dashing"
    #dockerfile: Dockerfile
    image: myros:eloquent
    container_name: ros2
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - ./ws:/root/ws:rw

  # entrypoint: bash
    command: "bash"
    working_dir: /root

    tty: true
    stdin_open: true
